apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shuhong-tasklist
  name: shuhong-tasklist2
  namespace: lawson-lu2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shuhong-tasklist2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /tasks
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: shuhong-tasklist2
    spec:
      containers:
      - image: ghcr.io/thg-accelerator/shuhong-tasklist2:v1.0.1
        imagePullPolicy: IfNotPresent
        name: shuhong-tasklist
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-creds
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
