apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2024-02-03T10:06:19Z","generation":4,"labels":{"app":"shuhong-tasklist"},"name":"shuhong-tasklist","namespace":"lawson-lu","resourceVersion":"133274483","uid":"ef1676fe-a298-4e74-86d5-ee94e6a27151"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"shuhong-tasklist"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"shuhong-tasklist"}},"spec":{"containers":[{"image":"ghcr.io/thg-accelerator/shuhong-tasklist:v0.0.0","imagePullPolicy":"IfNotPresent","name":"shuhong-tasklist","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"ghcr-creds"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2024-02-03T10:06:19Z","lastUpdateTime":"2024-02-03T10:06:19Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2024-02-03T10:53:32Z","lastUpdateTime":"2024-02-03T10:53:32Z","message":"ReplicaSet \"shuhong-tasklist-75cbf99597\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":4,"replicas":2,"unavailableReplicas":2,"updatedReplicas":1}}
  creationTimestamp: "2024-02-03T10:06:19Z"
  generation: 11
  labels:
    app: shuhong-tasklist
  name: shuhong-tasklist
  namespace: lawson-lu
  resourceVersion: "134322759"
  uid: ef1676fe-a298-4e74-86d5-ee94e6a27151
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shuhong-tasklist
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /tasks
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: shuhong-tasklist
    spec:
      containers:
      - image: ghcr.io/thg-accelerator/shuhong-tasklist:v0.0.1
        imagePullPolicy: IfNotPresent
        name: shuhong-tasklist
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-creds
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-02-05T14:45:15Z"
    lastUpdateTime: "2024-02-05T21:04:35Z"
    message: ReplicaSet "shuhong-tasklist-b4dc6c6cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-02-05T21:11:51Z"
    lastUpdateTime: "2024-02-05T21:11:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
