apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: shuhong-tasklist
  name: shuhong-tasklist
  namespace: lawson-lu
  resourceVersion: "134301861"
  uid: ef1676fe-a298-4e74-86d5-ee94e6a27151
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shuhong-tasklist
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
	prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: shuhong-tasklist
    spec:
      containers:
      - image: ghcr.io/thg-accelerator/shuhong-tasklist:v0.0.1
        imagePullPolicy: IfNotPresent
 	livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: shuhong-tasklist
	ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
	  limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
	volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-creds
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
	volumes:
      - configMap:
          defaultMode: 420
          name: witness-service-config
        name: config

