apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-1
  name: test-1
spec:
  containers:
  - image: artifactory.io.thehut.local:5000/alpine:latest
    name: test-1
    command: ["sh", "-c", "sleep 5000"]
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "15Mi"
        cpu: "150m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
